export default [
    {
        type: "kuće",
        title: "kuća br. 1",
        description: "opis kuće br. 1",
        image: "/images/listings/kuca1.jpg",
        size: 200,
        price: 100000,
    },
    {
        type: "kuće",
        title: "kuća br. 2",
        description: "opis kuće br. 2",
        image: "/images/listings/kuca2.jpg",
        size: 200,
        price: 200000,
    },
    {
        type: "kuće",
        title: "kuća br. 3",
        description: "opis kuće br. 3",
        image: "/images/listings/kuca3.jpg",
        size: 200,
        price: 300000,
    },
    {
        type: "kuće",
        title: "kuća br. 4",
        description: "opis kuće br. 4",
        image: "/images/listings/kuca4.jpg",
        size: 200,
        price: 400000,
    },
    {
        type: "kuće",
        title: "kuća br. 5",
        description: "opis kuće br. 5",
        image: "/images/listings/kuca5.jpg",
        size: 200,
        price: 500000,
    },
    {
        type: "stanovi",
        title: "stan br. 1",
        description: "opis stana br. 1",
        image: "/images/listings/stan1.jpg",
        size: 200,
        price: 300000,
    },
    {
        type: "stanovi",
        title: "stan br. 2",
        description: "opis stana br. 2",
        image: "/images/listings/stan2.jpg",
        size: 200,
        price: 400000,
    },
    {
        type: "stanovi",
        title: "stan br. 3",
        description: "opis kuće br. 3",
        image: "/images/listings/stan3.jpg",
        size: 200,
        price: 500000,
    },
]
